import { CoastalRegion, FishSpeciesInfo, FishingHotspot } from './types';
import stripedMulletImg from './assets/images/striped_mullet_fish_1790303948775.jpg';
import atlanticCroakerImg from './assets/images/atlantic_croaker_fish_1790303964453.jpg';
import atlanticSpotImg from './assets/images/atlantic_spot_fish_1790303976052.jpg';
import summerFlounderImg from './assets/images/summer_flounder_fish_1790303990604.jpg';
import stripedBassImg from './assets/images/striped_bass_fish_1790304002428.jpg';
import redDrumImg from './assets/images/red_drum_fish_1790304018661.jpg';
import spottedSeatroutImg from './assets/images/spotted_seatrout_fish_1790304033402.jpg';
import bluefishImg from './assets/images/bluefish_chopper_1790304045242.jpg';

export const COASTAL_REGIONS: CoastalRegion[] = [
  {
    id: 'va-beach',
    name: 'Virginia Beach & Chesapeake Bay (36.909, -76.096)',
    state: 'VA',
    center: { lat: 36.909, lng: -76.096 },
    zoom: 13,
    tideStation: 'Lynnhaven Inlet / Cape Henry NOAA #8638999'
  },
  {
    id: 'socal',
    name: 'Southern California (San Diego & OC)',
    state: 'CA',
    center: { lat: 32.8524, lng: -117.2713 },
    zoom: 11,
    tideStation: 'La Jolla Scripps Pier #9410230'
  },
  {
    id: 'norcal',
    name: 'San Francisco Bay & Coast',
    state: 'CA',
    center: { lat: 37.8199, lng: -122.4783 },
    zoom: 11,
    tideStation: 'Golden Gate Fort Point #9414290'
  },
  {
    id: 'fl-keys',
    name: 'Florida Keys & Biscayne Bay',
    state: 'FL',
    center: { lat: 24.7136, lng: -81.0858 },
    zoom: 10,
    tideStation: 'Vaca Key / Marathon #8723970'
  },
  {
    id: 'fl-tampa',
    name: 'Tampa Bay & Gulf Coast',
    state: 'FL',
    center: { lat: 27.6146, lng: -82.7411 },
    zoom: 11,
    tideStation: 'Sunshine Skyway Pier #8726520'
  },
  {
    id: 'tx-gulf',
    name: 'Galveston & Texas Coastal Bend',
    state: 'TX',
    center: { lat: 29.2882, lng: -94.8152 },
    zoom: 11,
    tideStation: 'Galveston Pier 21 #8771450'
  },
  {
    id: 'nc-outerbanks',
    name: 'Outer Banks & Cape Hatteras',
    state: 'NC',
    center: { lat: 35.2289, lng: -75.5298 },
    zoom: 10,
    tideStation: 'Cape Hatteras Fishing Pier #8654467'
  },
  {
    id: 'ny-montauk',
    name: 'Montauk Point & Long Island Sound',
    state: 'NY',
    center: { lat: 41.0712, lng: -71.8594 },
    zoom: 11,
    tideStation: 'Montauk Point Light #8510560'
  },
  {
    id: 'pnw-puget',
    name: 'Puget Sound & San Juan Islands',
    state: 'WA',
    center: { lat: 48.1172, lng: -122.7594 },
    zoom: 10,
    tideStation: 'Port Townsend Marine #9444900'
  }
];

export const FISHING_HOTSPOTS: FishingHotspot[] = [
  // Virginia Beach - Lesner Bridge
  {
    id: 'spot-lesner-bridge',
    name: 'Lesner Bridge & Lynnhaven Inlet',
    lat: 36.9077,
    lng: -76.1287,
    region: 'va-beach',
    subType: 'Pier & Jetty',
    targetSpecies: [
      'Striped Mullet (Jumping Mullet)',
      'Atlantic Croaker (Hardhead)',
      'Atlantic Spot',
      'Striped Bass (Rockfish)',
      'Summer Flounder (Fluke)',
      'Red Drum (Puppy Drum / Channel Bass)',
      'Spotted Seatrout (Specks)',
      'Bluefish'
    ],
    depthFt: '15 - 45 ft',
    bottomStructure: 'Bridge pilings, deep tidal scour trench, rubble and oyster beds',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Live spot', 'Jig heads with paddle tail swimbaits (pearl white)', 'Live fiddle crabs for sheepshead', 'Cut mullet'],
    access: 'Beach Access',
    rating: 4.9,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Heavy 3-4 knot tidal rip current through inlet gorge; boat wake traffic',
    description: 'Premier saltwater fishing corridor connecting the Chesapeake Bay with Lynnhaven River. Stripers and flounder position behind the massive bridge shadow lines and piling eddies feeding aggressively on moving tides.'
  },
  {
    id: 'spot-lynnhaven-pier-beach',
    name: 'Chic\'s Beach & Lynnhaven Inlet Mouth',
    lat: 36.9112,
    lng: -76.1345,
    region: 'va-beach',
    subType: 'Surf Fishing',
    targetSpecies: ['Red Drum (Puppy Drum)', 'Speckled Trout', 'Flounder', 'Spot', 'Croaker'],
    depthFt: '4 - 20 ft',
    bottomStructure: 'Sandbar channels, sandy points and inlet dropoffs',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Live bloodworms', 'Fishbites bloodworm strips', 'Carolina-rigged live shrimp', 'Gold spoons'],
    access: 'Beach Access',
    rating: 4.7,
    currentActivity: 'Active',
    hazards: 'Shifting sand drop-offs; strong tidal suction on outgoing tide',
    description: 'Wide sandy beach immediately adjacent to Lesner Bridge. Excellent surf casting for puppy drum, specks, and flounder during moving tides.'
  },
  // SoCal
  {
    id: 'spot-lj-kelp',
    name: 'La Jolla Kelp Beds & Cove',
    lat: 32.8488,
    lng: -117.2778,
    region: 'socal',
    subType: 'Reef / Offshore',
    targetSpecies: ['California Yellowtail', 'Calico Bass', 'White Seabass', 'California Halibut'],
    depthFt: '35 - 90 ft',
    bottomStructure: 'Giant kelp forest over sub-marine granite canyon edges',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Live Pacific Mackerel', 'Live Sardines', 'Surface Iron (Tady 45)', 'Weedless Swimbaits'],
    access: 'Boat Ramp / Kayak',
    rating: 4.9,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Heavy kelp entanglement, sea lions aggressively stealing catch, submerged boiler rocks',
    description: 'World-renowned destination for kayak anglers and boaters targeting prized Yellowtail and trophy White Seabass along the subsea canyon shelf.'
  },
  {
    id: 'spot-scripps-pier',
    name: 'Scripps Pier & Black\'s Beach Shore',
    lat: 32.8654,
    lng: -117.2544,
    region: 'socal',
    subType: 'Surf Fishing',
    targetSpecies: ['California Halibut', 'Corbina', 'Barred Surfperch', 'Yellowfin Croaker'],
    depthFt: '3 - 18 ft',
    bottomStructure: 'Sandbar gutters, rip-current cuts and marine drop-offs',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Live Sand Crabs (soft shell)', 'Mormystra ghost shrimp', 'Lucky Craft Flash Minnow 110', 'Carolina rig with Gulp! Camo sandworms'],
    access: 'Beach Access',
    rating: 4.7,
    currentActivity: 'Active',
    hazards: 'Strong rip currents, shorebreak surf',
    description: 'Prime surfcasting zone. Halibut wait in the depression cuts while Corbina graze right in inches of foam feeding on sand crabs during incoming flood tides.'
  },
  {
    id: 'spot-mission-bay-jetty',
    name: 'Mission Bay Channel South Jetty',
    lat: 32.7562,
    lng: -117.2531,
    region: 'socal',
    subType: 'Pier & Jetty',
    targetSpecies: ['Spotted Sand Bass', 'California Halibut', 'Pacific Bonito', 'Leopard Shark'],
    depthFt: '15 - 35 ft',
    bottomStructure: 'Quarry granite riprap rocks and fast tidal scour channels',
    tidePreference: 'Any Moving Water',
    bestBaits: ['Krocodile Spoons', 'Berkley Gulp Alive Jerk Shads', 'Squid strips on dropper loop', 'Live smelt'],
    access: 'Public Pier',
    rating: 4.5,
    currentActivity: 'Active',
    hazards: 'Slippery jetty rocks when wet, fast tidal water surge',
    description: 'Jetty corridor funneling baitfish into the ocean. Excellent casting platforms for pelagic surface cruisers and bottom ambush predators.'
  },
  {
    id: 'spot-ocean-beach-pier',
    name: 'Ocean Beach Pier & Point Loma Kelp',
    lat: 32.7482,
    lng: -117.2562,
    region: 'socal',
    subType: 'Pier & Jetty',
    targetSpecies: ['Barred Surfperch', 'Pacific Mackerel', 'Calico Bass', 'California Halibut'],
    depthFt: '20 - 40 ft',
    bottomStructure: 'Sand with scattered submerged patch reefs',
    tidePreference: 'Slack High',
    bestBaits: ['Cut anchovy', 'Sabiki rigs for bait', 'Squid', 'Ghost shrimp'],
    access: 'Public Pier',
    rating: 4.4,
    currentActivity: 'Moderate',
    description: 'One of the longest concrete piers on the Pacific coast. Deep end reaches clear ocean currents holding bonito, mackerel and bottom flatfish.'
  },

  // NorCal
  {
    id: 'spot-fort-point',
    name: 'Fort Point & Golden Gate Tide Rip',
    lat: 37.8105,
    lng: -122.4771,
    region: 'norcal',
    subType: 'Inshore Bay',
    targetSpecies: ['Striped Bass', 'California Halibut', 'Lingcod', 'Rockfish'],
    depthFt: '25 - 65 ft',
    bottomStructure: 'Granite boulder fields under heavy Pacific rip currents',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Hair Raiser jigs with white curl tails', 'Live anchovy', 'Swim shads', 'Bucktails'],
    access: 'Park / Trail',
    rating: 4.8,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Dangerous undertow, sudden large ocean swells striking rocks',
    description: 'Iconic spot right beneath the Golden Gate Bridge. Stripers stage behind rock eddies to ambush crabs and baitfish swept out by the powerful bay ebb.'
  },
  {
    id: 'spot-pacifica-pier',
    name: 'Pacifica Pier & Sharp Park Beach',
    lat: 37.6321,
    lng: -122.4972,
    region: 'norcal',
    subType: 'Pier & Jetty',
    targetSpecies: ['King Salmon', 'Striped Bass', 'Barred Surfperch'],
    depthFt: '18 - 30 ft',
    bottomStructure: 'Pure sand beach break, turbulent upwelling',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Crab snare baited with squid/chicken', 'Anchovy cut bait', 'Gibbs minnow'],
    access: 'Public Pier',
    rating: 4.6,
    currentActivity: 'Active',
    hazards: 'Heavy marine fog, freezing winds',
    description: 'Famous along the West Coast for massive winter crab runs and summer salmon runs within casting distance of the pier railing.'
  },
  {
    id: 'spot-berkeley-flats',
    name: 'Berkeley Flats & Emeryville Reef',
    lat: 37.8542,
    lng: -122.3385,
    region: 'norcal',
    subType: 'Estuary & Flats',
    targetSpecies: ['California Halibut', 'Striped Bass', 'White Sturgeon'],
    depthFt: '8 - 22 ft',
    bottomStructure: 'Mud and shell beds, shallow warming flats',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Drifting live shiners', 'Frozen anchovies', 'Ghost shrimp on sliding sinker'],
    access: 'Boat Ramp / Kayak',
    rating: 4.5,
    currentActivity: 'Moderate',
    description: 'Broad protected flats in San Francisco Bay that warm up quickly, drawing aggressive Halibut to feed as tide rises over the mud shoals.'
  },

  // Florida Keys
  {
    id: 'spot-7mile-bridge',
    name: 'Seven Mile Bridge Channel (Pigeon Key)',
    lat: 24.6974,
    lng: -81.1602,
    region: 'fl-keys',
    subType: 'Pier & Jetty',
    targetSpecies: ['Atlantic Tarpon', 'Mangrove Snapper', 'Jack Crevalle', 'Goliath Grouper'],
    depthFt: '12 - 32 ft',
    bottomStructure: 'Deep coral-limestone channel with huge bridge pillings',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Live Pinfish', 'Live Blue Crab drifted on current', 'Threadfin Herring', 'D.O.A. TerrorEyz'],
    access: 'Park / Trail',
    rating: 4.9,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Screaming 4-knot tidal currents, sharks chasing hooked tarpon',
    description: 'Legendary Atlantic-to-Gulf corridor. Massive schools of Tarpon roll on outbound spring tides gorging on drifting blue crabs and pilchards.'
  },
  {
    id: 'spot-bahia-honda',
    name: 'Bahia Honda Channel & Rail Bridge',
    lat: 24.6582,
    lng: -81.2811,
    region: 'fl-keys',
    subType: 'Inshore Bay',
    targetSpecies: ['Atlantic Tarpon', 'Mutton Snapper', 'Bonefish', 'Great Barracuda'],
    depthFt: '15 - 45 ft',
    bottomStructure: 'Limestone trench separating crystalline Florida Bay from open Atlantic',
    tidePreference: 'Any Moving Water',
    bestBaits: ['Silver spoons', 'Live jumbo shrimp', 'Crab float rigs', 'Spool jigs'],
    access: 'Boat Ramp / Kayak',
    rating: 4.8,
    currentActivity: 'Prime (Feeding)',
    description: 'Deepest natural pass in the Florida Keys. Crystal-clear turquoise water where you can spot cruising tarpon and jacks before pitching your cast.'
  },
  {
    id: 'spot-islamorada-flats',
    name: 'Islamorada Backcountry & Turtle Grass Flats',
    lat: 24.9312,
    lng: -80.6273,
    region: 'fl-keys',
    subType: 'Estuary & Flats',
    targetSpecies: ['Bonefish', 'Common Snook', 'Red Drum', 'Permit'],
    depthFt: '1 - 6 ft',
    bottomStructure: 'Lush turtle grass shoals, marl mud mounds and pot holes',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Live crab', 'Live glass minnow', 'Gotcha Clouser Minnow fly', 'Shrimp jigs'],
    access: 'Boat Ramp / Kayak',
    rating: 5.0,
    currentActivity: 'Active',
    hazards: 'Extremely shallow coral heads, fragile sea grass beds (idle zone)',
    description: 'The Sportfishing Capital of the World. Sight-casting tailing bonefish and cruising permit in skin-deep crystal flats.'
  },

  // Florida Tampa
  {
    id: 'spot-skyway-south',
    name: 'Sunshine Skyway South Fishing Pier',
    lat: 27.6041,
    lng: -82.6568,
    region: 'fl-tampa',
    subType: 'Pier & Jetty',
    targetSpecies: ['Spanish Mackerel', 'Common Snook', 'Mangrove Snapper', 'Red Drum'],
    depthFt: '20 - 45 ft',
    bottomStructure: 'Artificial limestone reef balls and old concrete bridge supports',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Got-Cha Plugs (gold hook)', 'Sabiki bait rigs for greenbacks', 'Live pinfish bottom bounced'],
    access: 'Public Pier',
    rating: 4.8,
    currentActivity: 'Prime (Feeding)',
    description: 'The longest fishing pier in the world. Cars drive right onto the deck with 24/7 access to the mouth of Tampa Bay.'
  },
  {
    id: 'spot-fort-desoto',
    name: 'Fort De Soto Gulf Pier & Sand Key Pass',
    lat: 27.6152,
    lng: -82.7369,
    region: 'fl-tampa',
    subType: 'Pier & Jetty',
    targetSpecies: ['Common Snook', 'Red Drum', 'Spotted Seatrout', 'Florida Pompano'],
    depthFt: '10 - 24 ft',
    bottomStructure: 'Sandy dropoffs adjacent to mangrove barrier keys',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Live scaled sardines', 'Doc\'s Goofy Jigs for Pompano', 'Jumbo live shrimp'],
    access: 'Public Pier',
    rating: 4.7,
    currentActivity: 'Active',
    description: 'Gateway to the open Gulf. High tidal flow creates sweeping current eddies holding massive schools of ambush Snook.'
  },

  // Texas Gulf
  {
    id: 'spot-galveston-jetties',
    name: 'Galveston South Jetty & Channel Pass',
    lat: 29.3371,
    lng: -94.7176,
    region: 'tx-gulf',
    subType: 'Pier & Jetty',
    targetSpecies: ['Red Drum', 'Spotted Seatrout', 'Southern Flounder', 'Black Drum'],
    depthFt: '14 - 38 ft',
    bottomStructure: 'Granite boulder breakwater extending 5 miles into Gulf waters',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Cracked Blue Crab', 'Live finger mullet', 'Soft plastics on jighead', 'Glow DOA shrimp'],
    access: 'Boat Ramp / Kayak',
    rating: 4.8,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Extreme ship wake from container vessels, slick barnacles',
    description: 'World-famous Texas trophy Redfish run hotspot. Over five miles of granite boulders extending straight into the Gulf current.'
  },
  {
    id: 'spot-san-luis-pass',
    name: 'San Luis Pass Toll & Marshes',
    lat: 29.0792,
    lng: -95.1219,
    region: 'tx-gulf',
    subType: 'Estuary & Flats',
    targetSpecies: ['Spotted Seatrout', 'Red Drum', 'Southern Flounder'],
    depthFt: '4 - 18 ft',
    bottomStructure: 'Constantly shifting submerged sandbars and bay oyster reefs',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Live shrimp under popping cork', 'MirrOlure 52MR', 'Berkley Gulp Swimming Mullet'],
    access: 'Beach Access',
    rating: 4.6,
    currentActivity: 'Active',
    hazards: 'DANGEROUS CURRENT: Strictly NO wading/swimming in the main throat; fish from sandbar bank',
    description: 'Enormous tidal exchange between West Galveston Bay and open Gulf. Epic flounder gigging and fall trout migration corridor.'
  },

  // North Carolina Outer Banks
  {
    id: 'spot-cape-point',
    name: 'Cape Point - Buxton (The Tip of Hatteras)',
    lat: 35.2184,
    lng: -75.5262,
    region: 'nc-outerbanks',
    subType: 'Surf Fishing',
    targetSpecies: ['Red Drum', 'Bluefish', 'Striped Bass', 'Spanish Mackerel'],
    depthFt: '6 - 25 ft',
    bottomStructure: 'Where the Labrador Current collides with the warm Gulf Stream over Diamond Shoals',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Fresh bunker (menhaden) chunk on fish-finder rig', 'Stingsilver spoons', 'Mullet head'],
    access: 'Beach Access',
    rating: 5.0,
    currentActivity: 'Prime (Feeding)',
    hazards: '4WD beach driving required, severe sudden coastal undertows',
    description: 'The Mecca of East Coast surfcasting. Giant 40-50 lb red drum feed right in the thundering wash where two gigantic ocean currents clash.'
  },
  {
    id: 'spot-rodanthe-pier',
    name: 'Rodanthe Pier & Outer Sandbars',
    lat: 35.5962,
    lng: -75.4647,
    region: 'nc-outerbanks',
    subType: 'Pier & Jetty',
    targetSpecies: ['Spanish Mackerel', 'Florida Pompano', 'Red Drum', 'Bluefish'],
    depthFt: '15 - 28 ft',
    bottomStructure: 'Pounding Atlantic ocean swells over deep coastal sloughs',
    tidePreference: 'Incoming (Flood)',
    bestBaits: ['Pin rigs with live bluefish for King Mackerel', 'Diamond Jigs', 'Bloodworms for pompano'],
    access: 'Public Pier',
    rating: 4.7,
    currentActivity: 'Active',
    description: 'Historic wooden Atlantic pier jutting deep into the migrating schools of pelagics cruising the Atlantic Flyway.'
  },

  // Montauk Point NY
  {
    id: 'spot-montauk-bluffs',
    name: 'Montauk Lighthouse Bluffs & The Rip',
    lat: 41.0715,
    lng: -71.8561,
    region: 'ny-montauk',
    subType: 'Surf Fishing',
    targetSpecies: ['Striped Bass', 'Bluefish', 'Summer Flounder (Fluke)', 'False Albacore'],
    depthFt: '10 - 45 ft',
    bottomStructure: 'Massive glacial erratic boulders and roaring rips at the tip of Long Island',
    tidePreference: 'Outgoing (Ebb)',
    bestBaits: ['Super Strike Darter', 'Needlefish plugs', 'Live eels drifted at night', 'Bucktails with pork rind'],
    access: 'Park / Trail',
    rating: 5.0,
    currentActivity: 'Prime (Feeding)',
    hazards: 'Extreme slippery weed-covered boulders (korkers spiked boots mandatory), rogue breakers',
    description: 'The Surfcasting Capital of the World. Fall migration blitzes produce legendary 40+ pound striped bass crashing pods of peanut bunker in the rocks.'
  },

  // PNW Puget Sound
  {
    id: 'spot-point-defiance',
    name: 'Point Defiance & The Tacoma Narrows Rip',
    lat: 47.3115,
    lng: -122.5358,
    region: 'pnw-puget',
    subType: 'Inshore Bay',
    targetSpecies: ['Chinook (King) Salmon', 'Coho (Silver) Salmon', 'Lingcod', 'Cabezon'],
    depthFt: '40 - 160 ft',
    bottomStructure: 'Steep underwater dropoffs with deep gravel bars and intense tidal back-eddies',
    tidePreference: 'Slack Low',
    bestBaits: ['Point Wilson Dart jigs (nickel/blue)', 'Mooched whole herring with slip sinker', 'Buzz Bomb jigs'],
    access: 'Boat Ramp / Kayak',
    rating: 4.8,
    currentActivity: 'Active',
    hazards: '6+ knot tidal rips swirling through Narrows; careful boating required',
    description: 'Renowned Pacific Northwest salmon haven. Salmon follow bait balls squeezed tightly through the Tacoma Narrows gorge on every tide transition.'
  }
];

export const FISH_SPECIES_CATALOG: FishSpeciesInfo[] = [
  {
    id: 'striped-bass',
    name: 'Striped Bass (Rockfish)',
    scientificName: 'Morone saxatilis',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '2 - 35 ft',
    idealTide: 'Outgoing ebb tide past structure & boulders',
    idealWaterTemp: '54°F - 66°F',
    preferredBaitsAndLures: ['SP Minnow', 'Bucktail jig with red pork rind trailer', 'Live eels (night)', 'Super Strike Popper'],
    regulationSummary: 'Slot limit: 20" - 31" (Bay); 1-2 fish/person daily depending on season.',
    minSize: '20" - 31" Slot Limit',
    bagLimit: '1 - 2 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh. Striped bass tagging quota & VMRC commercial permit required.',
    edibilityRating: 5,
    difficultyRating: 4,
    tips: 'Stripers cruise current rips under bridge shadow lines. Move nets or drift jigs along the drop-off contour lines.',
    badgeColor: 'blue',
    photoUrl: stripedBassImg
  },
  {
    id: 'red-drum',
    name: 'Red Drum (Puppy Drum / Channel Bass)',
    scientificName: 'Sciaenops ocellatus',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '1 - 25 ft',
    idealTide: 'Rising incoming tide flooding grass flats & sandbars',
    idealWaterTemp: '65°F - 78°F',
    preferredBaitsAndLures: ['Half blue crab', 'Live finger mullet', 'Gold weedless spoon', 'DOA scented shrimp under cork'],
    regulationSummary: '18" - 26" slot limit; 3 fish per person daily limit (VA).',
    minSize: '18" - 26" Slot Limit',
    bagLimit: '3 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh. Strictly prohibit keeping oversized broodstock red drum (>26").',
    edibilityRating: 4,
    difficultyRating: 3,
    tips: 'School along sand ridges and shallow shoals. Extremely sensitive to tide direction.',
    badgeColor: 'orange',
    photoUrl: redDrumImg
  },
  {
    id: 'summer-flounder',
    name: 'Summer Flounder (Fluke)',
    scientificName: 'Paralichthys dentatus',
    category: 'Bottom / Reef',
    seasonalStatus: 'Peak Season',
    activeDepth: '5 - 50 ft',
    idealTide: 'Moving water along drop-off channel edges',
    idealWaterTemp: '58°F - 72°F',
    preferredBaitsAndLures: ['Live minnow / silverside', 'Squid strips on bucktail', 'Gulp! Swimming Mullet 4"'],
    regulationSummary: '16" min total length; 4 fish per person daily limit (VA).',
    minSize: '16" Min Length',
    bagLimit: '4 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh (targeted flounder nets use 5½"+ to ensure 16" legal minimum).',
    edibilityRating: 5,
    difficultyRating: 3,
    tips: 'Lie motionless camouflaged on sandy/mud bottom channel edges waiting for tide to sweep baitfish overhead.',
    badgeColor: 'amber',
    photoUrl: summerFlounderImg
  },
  {
    id: 'speckled-trout',
    name: 'Spotted Seatrout (Specks)',
    scientificName: 'Cynoscion nebulosus',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '3 - 15 ft',
    idealTide: 'Incoming moving tide over grass beds & channel edges',
    idealWaterTemp: '60°F - 74°F',
    preferredBaitsAndLures: ['Live shrimp under popping cork', 'MirrOlure Catch 2000', 'Soft paddle tail jigs'],
    regulationSummary: '14" min total length; 5 fish per person daily limit (only 1 over 24" allowed).',
    minSize: '14" Min (Max 1 >24")',
    bagLimit: '5 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh. Harvest subject to commercial license seasons.',
    edibilityRating: 5,
    difficultyRating: 3,
    tips: 'Cruise shallow grass flats during early incoming tide, retreating to deeper channels when tide falls.',
    badgeColor: 'indigo',
    photoUrl: spottedSeatroutImg
  },
  {
    id: 'atlantic-croaker',
    name: 'Atlantic Croaker (Hardhead)',
    scientificName: 'Micropogonias undulatus',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '4 - 35 ft',
    idealTide: 'Moving ebb and flood tides over mud & shell bottoms',
    idealWaterTemp: '62°F - 76°F',
    preferredBaitsAndLures: ['Peeling bloodworms', 'Squid strips', 'Fishbites bloodworm flavor', 'Cut mullet strips'],
    regulationSummary: 'No minimum size limit in Virginia (VMRC). Possession limit is 50 fish per person per day.',
    minSize: 'No Minimum Size',
    bagLimit: '50 fish / day',
    gillNetInfo: 'Gill Net: Primary gill net target! VMRC minimum mesh size is 2 7/8" stretched mesh. No minimum fish size; 50 fish/day possession limit.',
    edibilityRating: 5,
    difficultyRating: 1,
    tips: 'Makes a distinctive drumming/croaking sound. Heavily caught in commercial and recreational gill nets as schools migrate along inlet trenches.',
    badgeColor: 'emerald',
    photoUrl: atlanticCroakerImg
  },
  {
    id: 'striped-mullet',
    name: 'Striped Mullet (Jumping Mullet)',
    scientificName: 'Mugil cephalus',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '1 - 20 ft',
    idealTide: 'Incoming flood tide over shallow mud flats and channel edges',
    idealWaterTemp: '65°F - 80°F',
    preferredBaitsAndLures: ['Cast net', 'Runaround gill net', 'Dough ball / bread with tiny hook'],
    regulationSummary: 'No minimum size limit; open harvest for food & bait under VMRC rules.',
    minSize: 'No minimum size',
    bagLimit: 'No limit (or commercial quota)',
    gillNetInfo: 'Gill Net: YES, quintessential gill net fish! VMRC minimum mesh size is 2 7/8" stretched mesh. One of the top species harvested by Virginia gill netters for roe and fresh bait.',
    edibilityRating: 4,
    difficultyRating: 2,
    tips: 'Herbivorous bottom feeder that feeds on micro-algae & detritus—rarely bites a standard hook, making gill nets and cast nets the #1 way to harvest them in Lynnhaven & Chesapeake Bay.',
    badgeColor: 'teal',
    photoUrl: stripedMulletImg
  },
  {
    id: 'atlantic-spot',
    name: 'Atlantic Spot',
    scientificName: 'Leiostomus xanthurus',
    category: 'Inshore / Estuary',
    seasonalStatus: 'Peak Season',
    activeDepth: '3 - 25 ft',
    idealTide: 'Moving water in Lynnhaven Inlet and river channels',
    idealWaterTemp: '64°F - 78°F',
    preferredBaitsAndLures: ['Live bloodworms', 'Fishbites', 'Peeled shrimp'],
    regulationSummary: '50 fish per person daily limit; no minimum size limit.',
    minSize: 'No minimum size',
    bagLimit: '50 fish / day',
    gillNetInfo: 'Gill Net: YES, heavily harvested in 2 7/8" minimum mesh gill nets during the famous fall yellow-belly spot run.',
    edibilityRating: 5,
    difficultyRating: 1,
    tips: 'Prized panfish with sweet meat. School in huge numbers on sandy and shell bars.',
    badgeColor: 'amber',
    photoUrl: atlanticSpotImg
  },
  {
    id: 'bluefish',
    name: 'Bluefish',
    scientificName: 'Pomatomus saltatrix',
    category: 'Pelagic',
    seasonalStatus: 'Peak Season',
    activeDepth: 'Surface to 30 ft',
    idealTide: 'Fast moving outbound water through rips and bridge passes',
    idealWaterTemp: '58°F - 72°F',
    preferredBaitsAndLures: ['Hopkins spoon', 'Poppers', 'Cut menhaden chunk', 'Diamond jig'],
    regulationSummary: '3 fish/day (private anglers) / 5 fish/day (charter). No minimum size limit.',
    minSize: 'No minimum size',
    bagLimit: '3 - 5 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh. Sharp razor teeth require heavy twine gauge.',
    edibilityRating: 3,
    difficultyRating: 2,
    tips: 'Fierce feeding blitzes on moving tides. Target tide rip seams where baitfish get disoriented.',
    badgeColor: 'blue',
    photoUrl: bluefishImg
  },
  {
    id: 'spanish-mackerel',
    name: 'Spanish Mackerel',
    scientificName: 'Scomberomorus maculatus',
    category: 'Pelagic',
    seasonalStatus: 'Peak Season',
    activeDepth: 'Surface to 20 ft',
    idealTide: 'Incoming flood tide sweeping bait schools toward inlet mouth',
    idealWaterTemp: '68°F - 78°F',
    preferredBaitsAndLures: ['Got-Cha plug', 'Clarkspoon behind planer', 'Silver diamond jig'],
    regulationSummary: '14" min total length; 15 fish per person daily limit.',
    minSize: '14" Min Total Length',
    bagLimit: '15 fish / day',
    gillNetInfo: 'Gill Net: VMRC minimum mesh size is 2 7/8" stretched mesh. Surface net sets along inlet shoals.',
    edibilityRating: 4,
    difficultyRating: 2,
    tips: 'Speed predators. Fast retrieves right along surface current lanes produce instant hookups.',
    badgeColor: 'amber',
    photoUrl: 'https://images.unsplash.com/photo-1534043464124-3be32fe00099?auto=format&fit=crop&w=700&q=80'
  },
  {
    id: 'cal-halibut',
    name: 'California Halibut',
    scientificName: 'Paralichthys californicus',
    category: 'Surf',
    seasonalStatus: 'Peak Season',
    activeDepth: '4 - 60 ft',
    idealTide: 'Incoming flood to high slack tide',
    idealWaterTemp: '60°F - 68°F',
    preferredBaitsAndLures: ['Live Sardine or Smelt', 'Lucky Craft Flash Minnow 110', 'Dropshot white fluke swimbaits'],
    regulationSummary: '22" min total length; 5 fish per day south of Pt Conception (3 north).',
    minSize: '22" Min Total Length',
    bagLimit: '3 - 5 fish / day',
    gillNetInfo: 'Gill Net: Set gill nets subject to strict spatial depth closures to protect marine mammals.',
    edibilityRating: 5,
    difficultyRating: 4,
    tips: 'Ambush bottom hunter that hides buried under sand with only eyes exposed.',
    badgeColor: 'amber',
    photoUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=700&q=80'
  },
  {
    id: 'cal-yellowtail',
    name: 'California Yellowtail',
    scientificName: 'Seriola dorsalis',
    category: 'Pelagic',
    seasonalStatus: 'Peak Season',
    activeDepth: 'Surface down to 120 ft',
    idealTide: 'Ripping incoming tide around kelp points',
    idealWaterTemp: '64°F - 72°F',
    preferredBaitsAndLures: ['Surface Iron jigs', 'Live greenback mackerel', 'Live squid'],
    regulationSummary: '24" fork length minimum; 5 fish bag limit per angler.',
    minSize: '24" Min Fork Length',
    bagLimit: '5 fish / day',
    gillNetInfo: 'Gill Net: Drift gill nets heavily regulated with acoustic pingers in offshore waters.',
    edibilityRating: 5,
    difficultyRating: 5,
    tips: 'Hard fighting pelagic that runs straight into deep structure when hooked.',
    badgeColor: 'yellow',
    photoUrl: 'https://images.unsplash.com/photo-1534043464124-3be32fe00099?auto=format&fit=crop&w=700&q=80'
  }
];
